//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class BKSDisplayRenderOverlayDescriptor, NSData;

@interface _BKDisplayRenderOverlayPersistenceData : NSObject <NSSecureCoding>
{
    float _level;
    long long _overlayType;
    BKSDisplayRenderOverlayDescriptor *_descriptor;
    struct CGImage *_image;
    NSData *_imageData;
}

+ (_Bool)supportsSecureCoding;
+ (id)classesRequiredToDecode;
@property(nonatomic) float level; // @synthesize level=_level;
@property(nonatomic) struct CGImage *image; // @synthesize image=_image;
@property(retain, nonatomic) BKSDisplayRenderOverlayDescriptor *descriptor; // @synthesize descriptor=_descriptor;
@property(nonatomic) long long overlayType; // @synthesize overlayType=_overlayType;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)_initWithDescriptor:(id)arg1 overlayType:(long long)arg2 imageData:(id)arg3 level:(float)arg4;

@end

