//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface _BKHIDHumanPresenceSensorRecord : NSObject
{
    _Bool _humanIsPresent;
    unsigned long long _status;
    double _proximityInCentimeters;
    NSMutableArray *_services;
}

@property(retain, nonatomic) NSMutableArray *services; // @synthesize services=_services;
@property(nonatomic) _Bool humanIsPresent; // @synthesize humanIsPresent=_humanIsPresent;
@property(nonatomic) double proximityInCentimeters; // @synthesize proximityInCentimeters=_proximityInCentimeters;
@property(nonatomic) unsigned long long status; // @synthesize status=_status;
- (void)removeService:(id)arg1;
- (void)addService:(id)arg1;
- (void)_resetServiceStatus;
- (id)description;
- (void)dealloc;

@end

