//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKIOHIDService.h"

@interface _BKMockIOHIDService : BKIOHIDService
{
}

- (int)setElementValue:(unsigned int)arg1 forUsagePage:(unsigned int)arg2 usage:(unsigned int)arg3;
- (_Bool)setProperty:(id)arg1 forKey:(id)arg2;
- (id)propertyForKey:(id)arg1;
- (void)_observerWorkQueue_stopIOServiceRemovalNotifications;
- (void)_observerWorkQueue_startIOServiceRemovalNotifications;

@end

