//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKAccelerometerClient.h"

@interface BKAccelerometerClientBKSAccelerometer : BKAccelerometerClient
{
}

- (void)handleOrientationEvent:(long long)arg1 orientationLocked:(_Bool)arg2;
- (void)handleAccelerometerEventWithTimestamp:(double)arg1 x:(float)arg2 y:(float)arg3 z:(float)arg4 samplingInterval:(double)arg5;
- (void)_queue_invalidate;
- (_Bool)_deathBySendRight;
- (_Bool)_deathByPid;

@end

