//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface BKAccessibility : NSObject
{
}

+ (void)_setCapsLockLightOn:(_Bool)arg1;
+ (id)_eventRoutingClientConnectionManager;
+ (_Bool)_isDisplayBacklightOff;
+ (_Bool)_objectWithinProximity;
+ (struct CGPoint)_displayConvertToCAScreen:(struct CGPoint)arg1 withDisplayIntegerId:(unsigned int)arg2;
+ (struct CGPoint)_displayConvertFromCAScreen:(struct CGPoint)arg1 withDisplayIntegerId:(unsigned int)arg2;
+ (struct CGPoint)_displayConvertToCAScreen:(struct CGPoint)arg1;
+ (struct CGPoint)_displayConvertFromCAScreen:(struct CGPoint)arg1;
+ (CDUnknownFunctionPointerType)_accessibilityHIDEventTapCallback;
+ (void)_accessibilitySetHIDEventTapCallback:(CDUnknownFunctionPointerType)arg1;
+ (CDUnknownFunctionPointerType)_accessibilityEventTapCallback;
+ (void)_accessibilitySetEventTapCallback:(CDUnknownFunctionPointerType)arg1;
+ (void)_accessibilityProcessExternHIDEvent:(struct __IOHIDEvent *)arg1;

@end

