//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKGSEventClient.h"

@interface BKAccelerometerClient : BKGSEventClient
{
    float _xThreshold;
    float _yThreshold;
    float _zThreshold;
    _Bool _passiveOrientationEvents;
    _Bool _wantsOrientationEvents;
    _Bool _wantsAccelerometerEvents;
    double _accelerometerUpdateInterval;
    double _lastAccelerometerEventTimestamp;
}

@property(nonatomic, getter=_lastAccelerometerEventTimestamp, setter=_setLastAccelerometerEventTimestamp:) double lastAccelerometerEventTimestamp; // @synthesize lastAccelerometerEventTimestamp=_lastAccelerometerEventTimestamp;
@property(nonatomic) double accelerometerUpdateInterval; // @synthesize accelerometerUpdateInterval=_accelerometerUpdateInterval;
@property(nonatomic) _Bool wantsAccelerometerEvents; // @synthesize wantsAccelerometerEvents=_wantsAccelerometerEvents;
@property(nonatomic) _Bool wantsOrientationEvents; // @synthesize wantsOrientationEvents=_wantsOrientationEvents;
@property(nonatomic) _Bool passiveOrientationEvents; // @synthesize passiveOrientationEvents=_passiveOrientationEvents;
@property(nonatomic) float zThreshold; // @synthesize zThreshold=_zThreshold;
@property(nonatomic) float yThreshold; // @synthesize yThreshold=_yThreshold;
@property(nonatomic) float xThreshold; // @synthesize xThreshold=_xThreshold;
- (_Bool)_shouldSendSampleEventWithTimestamp:(double)arg1 samplingInterval:(double)arg2;
- (_Bool)_passesThresholdForX:(float)arg1 y:(float)arg2 z:(float)arg3;
- (void)_queue_invalidate;
- (void)handleOrientationEvent:(long long)arg1 orientationLocked:(_Bool)arg2;
- (void)handleAccelerometerEventWithTimestamp:(double)arg1 x:(float)arg2 y:(float)arg3 z:(float)arg4 samplingInterval:(double)arg5;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;

@end

