//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BKSProcessDelegate-Protocol.h"

@class BKSProcess, NSDictionary, NSString;
@protocol BKAlternateSystemAppDelegate, OS_dispatch_queue;

@interface BKAlternateSystemApp : NSObject <BKSProcessDelegate>
{
    NSString *_bundleID;
    id <BKAlternateSystemAppDelegate> _delegate;
    NSDictionary *_options;
    BKSProcess *_process;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)bundleInfoOverrides;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) BKSProcess *process; // @synthesize process=_process;
@property(copy, nonatomic) NSDictionary *options; // @synthesize options=_options;
@property(nonatomic) id <BKAlternateSystemAppDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
- (void)process:(id)arg1 didExitWithContext:(id)arg2;
@property(readonly, copy) NSString *description;
- (void)_noteExitedWithContext:(id)arg1;
- (void)_noteLaunchSucceeded;
- (void)_noteLaunchFailed:(int)arg1;
- (_Bool)terminate;
- (_Bool)launch;
- (void)dealloc;
- (id)initWithBundleId:(id)arg1 options:(id)arg2 queue:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

