//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BKBootUIOverlayVendor, BKDisplayRenderOverlay, BKDisplayRenderOverlayManager, BKSystemAppSentinel;
@protocol OS_dispatch_queue;

@interface BKBootUIPresenter : NSObject
{
    BKBootUIOverlayVendor *_bootUIOverlayVendor;
    BKSystemAppSentinel *_systemAppSentinel;
    BKDisplayRenderOverlayManager *_renderOverlayManager;
    BKDisplayRenderOverlay *_overlay;
    _Bool _isOverlaySustained;
    BKDisplayRenderOverlay *_underlay;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (id)sharedInstance;
- (void)_queue_removeUnderlay;
- (void)_queue_addUnderlay;
- (void)_queue_addOverlay;
- (void)_queue_removeOverlayWithAnimationSettings:(id)arg1;
- (void)_queue_updateOverlay;
- (void)_systemAppExited:(id)arg1;
- (void)_systemAppChanged:(id)arg1;
- (void)_systemAppFinishedLaunching:(id)arg1;
- (void)sustainOverlay;
- (void)dismissSustainedOverlayWithAnimationSettings:(id)arg1;
@property(readonly, nonatomic, getter=isShowingBootUI) _Bool showingBootUI;
- (id)description;
- (void)dealloc;
- (id)initWithSystemAppSentinel:(id)arg1 alternateSystemAppManager:(id)arg2 bootUIOverlayVendor:(id)arg3 renderOverlayManager:(id)arg4;

@end

