//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BKSButtonHapticsDefinition, BRButtonResolverController, NSMutableArray, NSMutableDictionary;
@protocol OS_dispatch_group, OS_dispatch_queue;

@interface BKButtonHapticsController : NSObject
{
    NSMutableArray *_clickStatesConfigured;
    NSMutableArray *_clickStatesPending;
    NSMutableDictionary *_assetCache;
    BKSButtonHapticsDefinition *_homeButtonDefinition;
    BRButtonResolverController *_BRController;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_group> *_controllerReadyGroup;
    long long _maximumPressCount;
    long long _maximumTapCount;
    double _multiplePressTimeInterval;
    double _longPressTimeInterval;
}

+ (id)sharedInstance;
@property(nonatomic) double longPressTimeInterval; // @synthesize longPressTimeInterval=_longPressTimeInterval;
@property(nonatomic) double multiplePressTimeInterval; // @synthesize multiplePressTimeInterval=_multiplePressTimeInterval;
@property(nonatomic) long long maximumTapCount; // @synthesize maximumTapCount=_maximumTapCount;
@property(nonatomic) long long maximumPressCount; // @synthesize maximumPressCount=_maximumPressCount;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *controllerReadyGroup; // @synthesize controllerReadyGroup=_controllerReadyGroup;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) BRButtonResolverController *BRController; // @synthesize BRController=_BRController;
@property(retain, nonatomic) BKSButtonHapticsDefinition *homeButtonDefinition; // @synthesize homeButtonDefinition=_homeButtonDefinition;
- (void)applyDefinitions:(id)arg1;
- (void)_queue_applyDefinitions:(id)arg1;
- (void)_queue_applyConfigurationChanges;
- (void)_queue_addChangesForPendingState:(id)arg1 configuredState:(id)arg2 toStates:(id)arg3 configs:(id)arg4 assets:(id)arg5 enable:(id)arg6 disable:(id)arg7;
- (void)_queue_addConfigsAndAssetsForClickState:(id)arg1 toStates:(id)arg2 configs:(id)arg3 assets:(id)arg4;
- (void)_queue_getSlowHapticType:(long long *)arg1 getMediumHapticType:(long long *)arg2 getFastHapticType:(long long *)arg3 fromAssetType:(long long)arg4 clickCount:(long long)arg5;
- (id)_queue_assetOfType:(long long)arg1 parameters:(id)arg2;
- (void)_configureSyncWithBlock:(CDUnknownBlockType)arg1;
- (void)_configureAsyncWithBlock:(CDUnknownBlockType)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithBHButtonHapticsController:(id)arg1;
- (id)init;

@end

