//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"

@class BSMutableSettings;

@interface BKButtonHapticsClickState : NSObject <NSCopying>
{
    BSMutableSettings *_settings;
}

+ (void)inspectChangesFromState:(id)arg1 toState:(id)arg2 withBlock:(CDUnknownBlockType)arg3;
+ (id)clickStateWithState:(unsigned long long)arg1;
@property(retain, nonatomic) BSMutableSettings *settings; // @synthesize settings=_settings;
@property(nonatomic, getter=isEnabled) _Bool enabled;
@property(nonatomic) double maximumTimeInterval;
@property(nonatomic) double minimumTimeInterval;
@property(readonly, nonatomic) long long hapticClickCount;
@property(readonly, nonatomic) _Bool shouldUseHaptic;
@property(nonatomic) long long assetType;
@property(nonatomic) unsigned long long clickState;
- (id)fastConfigDictionaryForHAButtonHapticType:(long long)arg1;
- (id)normalConfigDictionaryForHAButtonHapticType:(long long)arg1;
- (id)slowConfigDictionaryForHAButtonHapticType:(long long)arg1;
- (void)_applyGainForHapticType:(long long)arg1 toConfigDictionary:(id)arg2;
- (id)_baseConfigDictionary;
- (_Bool)_shouldUseDoublePressAssetForClickStateType:(unsigned long long)arg1;
- (_Bool)_shouldUseHapticForClickState:(unsigned long long)arg1;
- (_Bool)_isUpClickStateType:(unsigned long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (void)dealloc;
- (id)init;
- (id)_initWithSettings:(id)arg1;

@end

