//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BSInvalidatable-Protocol.h"

@class BSTimer, NSString;
@protocol OS_dispatch_queue;

@interface BKDisplayBrightnessUpdateTransaction : NSObject <BSInvalidatable>
{
    NSString *_identifier;
    NSObject<OS_dispatch_queue> *_queue;
    BSTimer *_timer;
    double _expirationTime;
    _Bool _invalidated;
}

+ (id)_sharedQueue;
+ (void)beginImplicitTransaction;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (void)_queue_updateExpirationTimeWithIntervalSinceNow:(double)arg1;
- (void)_queue_invalidate;
- (void)_queue_setTimerWithTimeIntervalSinceNow:(double)arg1;
- (void)invalidate;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

