//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKDisplayBootUIRenderOverlay.h"

@class BKImageSequence, CAKeyframeAnimation;

@interface BKDisplayRenderOverlaySpinny : BKDisplayBootUIRenderOverlay
{
    unsigned long long _background;
    BKImageSequence *_imageSequence;
    CAKeyframeAnimation *_animation;
}

+ (id)overlayWithLevel:(float)arg1 display:(id)arg2;
@property(nonatomic) unsigned long long background; // @synthesize background=_background;
- (id)_assetPrefix;
- (_Bool)_useLightBackground;
- (void)_unloadSpinnyImageSequence;
- (id)_spinnyImageSequence;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (void)_setScale:(double)arg1;
- (void)_cleanUpContentLayer;
- (id)_prepareContentLayerForPresentation:(id)arg1;
- (void)_stopAnimating;
- (void)_startAnimating;
- (void)dealloc;
- (id)initWithOverlayDescriptor:(id)arg1 level:(float)arg2;

@end

