//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BKDigitizerEventSchedulerBase, NSMapTable, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface BKDigitizerArbiterInfo : NSObject
{
    unsigned int _previousVendedTouchStreamReference;
    BKDigitizerEventSchedulerBase *_scheduler;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_perDisplayInfo;
    NSMapTable *_referenceToTouchStreamClientsMapping;
}

@property(nonatomic) unsigned int previousVendedTouchStreamReference; // @synthesize previousVendedTouchStreamReference=_previousVendedTouchStreamReference;
@property(retain, nonatomic) NSMapTable *referenceToTouchStreamClientsMapping; // @synthesize referenceToTouchStreamClientsMapping=_referenceToTouchStreamClientsMapping;
@property(retain, nonatomic) NSMutableDictionary *perDisplayInfo; // @synthesize perDisplayInfo=_perDisplayInfo;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) BKDigitizerEventSchedulerBase *scheduler; // @synthesize scheduler=_scheduler;
- (id)touchStreamClientForReference:(unsigned int)arg1;
- (unsigned int)addTouchStreamClient:(id)arg1 toDisplayUUID:(id)arg2;
- (void)enumerateTouchStreamsForAllDisplaysUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateDigitizersForAllDisplaysUsingBlock:(CDUnknownBlockType)arg1;
- (void)enumerateDigitizersForDisplay:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)touchStreamInfoForDisplayUUID:(id)arg1 createIfNeeded:(_Bool)arg2;
- (struct OpaqueBKDigitizerInfo *)infoForDigitizerService:(id)arg1 createIfNeeded:(_Bool)arg2;
- (id)_displayInfoForDisplay:(id)arg1 createIfNeeded:(_Bool)arg2;
- (void)digitizerServiceDidDetach:(id)arg1;
- (void)dealloc;
- (id)initWithQueue:(id)arg1 scheduler:(id)arg2;

@end

