//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKDigitizerEventSchedulerWithDisplayLink.h"

@class NSMutableArray;

@interface BKDigitizerEventSchedulerWithPostponementToNextVSync : BKDigitizerEventSchedulerWithDisplayLink
{
    NSMutableArray *_blocks;
    _Bool _dispatchingTouchesOnDisplayLink;
    double _currentTime;
}

@property(nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
- (void)_thread_scheduleEventWithBlock:(CDUnknownBlockType)arg1 event:(struct __IOHIDEvent *)arg2 clientTaskPort:(unsigned int)arg3;
- (void)_thread_displayLinkFired:(id)arg1;
- (void)_thread_dispatchEventBlockImmediately:(CDUnknownBlockType)arg1;
- (void)_thread_dispatchPendingEvents:(id)arg1;
- (void)_thread_dispatchEventBlockAtNextVSync:(CDUnknownBlockType)arg1;
- (_Bool)_thread_shouldDispatchUsingDisplayLinkAtTime:(double)arg1;
- (double)_thread_positionWithinCurrentFrameAtTime:(double)arg1 duration:(double *)arg2;
- (void)dealloc;
- (id)init;

@end

