//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKDigitizerEventSchedulerBase.h"

@class CADisplayLink, NSThread;

@interface BKDigitizerEventSchedulerWithDisplayLink : BKDigitizerEventSchedulerBase
{
    CADisplayLink *_displayLink;
    NSThread *_thread;
}

+ (Class)displayLinkClass;
@property(readonly, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
- (void)scheduleEvent:(struct __IOHIDEvent *)arg1 fromDigitizer:(struct OpaqueBKDigitizerInfo *)arg2 toClient:(unsigned int)arg3;
- (void)_thread_scheduleEventWithBlock:(CDUnknownBlockType)arg1 event:(struct __IOHIDEvent *)arg2 clientTaskPort:(unsigned int)arg3;
- (void)_thread_displayLinkFired:(id)arg1;
- (void)performSync:(CDUnknownBlockType)arg1;
- (void)performAsync:(CDUnknownBlockType)arg1;
- (void)_performBlock:(CDUnknownBlockType)arg1;
- (void)_thread_startRunLoop;
- (void)dealloc;
- (id)init;

@end

