//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKProximitySensorHardwareBase.h"

@class BKIOHIDService;

@interface BKDiscreteProximitySensorHardware : BKProximitySensorHardwareBase
{
    _Bool _pocketTouchesExpected;
    BKIOHIDService *_proximityService;
}

@property(retain) BKIOHIDService *proximityService; // @synthesize proximityService=_proximityService;
- (void)_setPocketTouchesExpected:(_Bool)arg1;
- (id)lowLevelDescriptionForMode:(long long)arg1 pocketTouchesExpected:(_Bool)arg2;
- (void)reallySetMode:(long long)arg1 pocketTouchesExpected:(_Bool)arg2;
- (void)reallyResetCalibration;
- (_Bool)isValidEvent:(struct __IOHIDEvent *)arg1 fromSender:(id)arg2;
- (void)dealloc;
- (id)init;

@end

