//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

@interface BKDigitizerTouchStreamAggregate : NSObject
{
    NSString *_displayUUID;
    NSMutableArray *_clients;
}

@property(readonly, nonatomic) NSMutableArray *clients; // @synthesize clients=_clients;
@property(copy, nonatomic) NSString *displayUUID; // @synthesize displayUUID=_displayUUID;
- (_Bool)getAmbiguityRecommendation:(unsigned char *)arg1 dispatchMode:(unsigned char *)arg2;
- (void)removeClient:(id)arg1;
- (void)addClient:(id)arg1;
- (void)enumerateClients:(CDUnknownBlockType)arg1;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)description;
- (void)invalidate;
- (void)dealloc;

@end

