//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSLock;

@interface BKDisplayBrightnessInterface : NSObject
{
    int _numPendingTransactions;
    _Bool _commitPending;
    float _systemDisplayBrightness;
    _Bool _shouldRestoreSystemBrightness;
    id _notificationObserver;
    NSLock *_lock;
}

+ (id)sharedInstance;
- (int)displayBrightnessCurve;
- (float)displayBrightness;
- (void)setAutoBrightnessEnabled:(_Bool)arg1;
- (void)setDisplayBrightnessCurve:(int)arg1;
- (void)restoreSystemDisplayBrightness;
- (float)systemDisplayBrightness;
- (void)setDisplayBrightness:(float)arg1 permanently:(_Bool)arg2;
- (void)_lock_commitDisplayBrightness;
- (void)synchronizeALSPreferencesAndDisplayBrightness;
- (void)_endUpdateTransaction:(id)arg1;
- (void)_beginUpdateTransaction:(id)arg1;
- (void)_postDisplayBrightnessChangedForUIKit;
- (void)_lock_addBrightnessObserver;
- (void)_lock_removeBrightnessObserver;
- (void)dealloc;
- (id)init;

@end

