//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKDisplayRenderOverlay.h"

#import "CAAnimationDelegate-Protocol.h"

@class CAContext, CALayer, NSString;

@interface BKDisplayBootUIRenderOverlay : BKDisplayRenderOverlay <CAAnimationDelegate>
{
    CALayer *_backgroundLayer;
    unsigned long long _outstandingAnimationsCount;
    _Bool _lightBackground;
    CAContext *_context;
    CALayer *_contentLayer;
}

@property(readonly, nonatomic) CALayer *contentLayer; // @synthesize contentLayer=_contentLayer;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)_animationForBackgroundLayerCrossfading:(id)arg1;
- (id)_animationForContentLayerCrossfading:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)_cleanUpContentLayer;
- (id)_prepareContentLayerForPresentation:(id)arg1;
- (void)_cleanup;
- (void)_freeze;
- (void)_dismissWithAnimationSettings:(id)arg1;
- (_Bool)_presentWithAnimationSettings:(id)arg1;
- (_Bool)disablesDisplayUpdates;
@property(nonatomic, getter=_bounds, setter=_setBounds:) struct CGRect bounds;
@property(readonly, nonatomic, getter=_useLightBackground) _Bool lightBackground; // @synthesize lightBackground=_lightBackground;
- (void)dealloc;
- (id)initWithOverlayDescriptor:(id)arg1 level:(float)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

