//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BKIOHIDServiceDisappearanceObserver-Protocol.h"
#import "BKIOHIDServiceMatchObserver-Protocol.h"

@class BKDigitizerArbiterInfo, BKIOHIDService, BKIOHIDServiceMatcher, NSString;
@protocol OS_dispatch_group, OS_dispatch_queue;

@interface BKDigitizerArbiterAccess : NSObject <BKIOHIDServiceMatchObserver, BKIOHIDServiceDisappearanceObserver>
{
    NSObject<OS_dispatch_queue> *_queue;
    BKDigitizerArbiterInfo *_arbiterInfo;
    NSObject<OS_dispatch_group> *_waitForMainDisplayGroup;
    BKIOHIDServiceMatcher *_digitizerMatcher;
    BKIOHIDService *_mainDisplayDigitizerService;
}

@property(retain) BKIOHIDService *mainDisplayDigitizerService; // @synthesize mainDisplayDigitizerService=_mainDisplayDigitizerService;
- (void)digitizerServiceDidDetach:(id)arg1;
- (void)accessAsynchronously:(CDUnknownBlockType)arg1;
- (void)accessSynchronously:(CDUnknownBlockType)arg1;
- (void)waitForMainDisplayDigitizerService;
- (void)serviceDidDisappear:(id)arg1;
- (void)matcher:(id)arg1 servicesDidMatch:(id)arg2;
- (void)dealloc;
- (id)initWithScheduler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

