//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BKDigitizerTouchStreamAggregate, NSMapTable;

@interface BKDigitizerArbiterInfoPerDisplay : NSObject
{
    NSMapTable *_digitizerServiceToInfoMapping;
    BKDigitizerTouchStreamAggregate *_touchStreams;
}

@property(retain, nonatomic) BKDigitizerTouchStreamAggregate *touchStreams; // @synthesize touchStreams=_touchStreams;
@property(retain, nonatomic) NSMapTable *digitizerServiceToInfoMapping; // @synthesize digitizerServiceToInfoMapping=_digitizerServiceToInfoMapping;
- (void)dealloc;
- (void)removeDigitizerInfoForService:(id)arg1;
- (struct OpaqueBKDigitizerInfo *)digitizerInfoForService:(id)arg1;

@end

