//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKDisplayRenderOverlay.h"

#import "CAAnimationDelegate-Protocol.h"

@class CAContext, NSString;

@interface BKDisplayRenderOverlayImage : BKDisplayRenderOverlay <CAAnimationDelegate>
{
    CAContext *_context;
    struct CGImage *_imageRef;
}

- (_Bool)_applyProgressIndicatorPropertiesToKernelIfNecessary;
- (id)_animationForKeyPath:(id)arg1 withSettings:(id)arg2;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)_cleanup;
- (id)_persistenceData;
- (void)_dismissWithAnimationSettings:(id)arg1;
- (void)_freeze;
- (_Bool)_presentWithAnimationSettings:(id)arg1;
- (_Bool)disablesDisplayUpdates;
@property(readonly, nonatomic) struct CGImage *image;
- (void)dealloc;
- (id)_initWithPersistenceData:(id)arg1;
- (id)initWithOverlayDescriptor:(id)arg1 level:(float)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

