//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BSDescriptionProviding-Protocol.h"

@class BSMachPortSendRight, BSPortDeathSentinel, BSProcessDeathWatcher, NSString;
@protocol BKEventClientDelegate, OS_dispatch_queue;

@interface BKEventClient : NSObject <BSDescriptionProviding>
{
    NSObject<OS_dispatch_queue> *_queue;
    id <BKEventClientDelegate> _queue_delegate;
    BSMachPortSendRight *_queue_sendRight;
    BSProcessDeathWatcher *_queue_pidWatcher;
    BSPortDeathSentinel *_queue_portSentinel;
    NSString *_queue_procName;
    int _queue_pid;
    _Bool _queue_invalidated;
}

@property(readonly, retain, nonatomic) BSMachPortSendRight *sendRight; // @synthesize sendRight=_queue_sendRight;
@property(readonly, nonatomic) int pid; // @synthesize pid=_queue_pid;
- (void)_queue_performDelegateCallout:(CDUnknownBlockType)arg1;
- (void)_queue_invalidate;
- (_Bool)_deathBySendRight;
- (_Bool)_deathByPid;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (void)invalidate;
@property(nonatomic) id <BKEventClientDelegate> delegate;
- (void)dealloc;
- (id)initWithPid:(int)arg1 sendRight:(id)arg2 queue:(id)arg3 processName:(id)arg4;
- (id)initWithPid:(int)arg1 sendRight:(id)arg2 queue:(id)arg3;
- (id)initWithPid:(int)arg1 sendRight:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

