//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <BaseBoard/BSBaseXPCServer.h>

@class NSObject;
@protocol OS_dispatch_queue;

@interface BKFenceArbiterServer : BSBaseXPCServer
{
    NSObject<OS_dispatch_queue> *_requestFenceQueue;
    NSObject<OS_dispatch_queue> *_createAssertionQueue;
}

- (void)queue_handleMessage:(id)arg1 client:(id)arg2;
- (void)dealloc;
- (id)initWithServiceName:(id)arg1 onQueue:(id)arg2;

@end

