//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BKFenceArbiterServer, BSAtomicSignal, BSMachPortReceiveRight, BSMachPortSendRight, CAContext;
@protocol OS_dispatch_queue, OS_dispatch_semaphore;

@interface BKFenceArbiter : NSObject
{
    BKFenceArbiterServer *_server;
    CAContext *_context;
    NSObject<OS_dispatch_queue> *_transactionQueue;
    NSObject<OS_dispatch_semaphore> *_fenceLock;
    NSObject<OS_dispatch_semaphore> *_fenceSemaphore;
    _Bool _fenceRunning;
    unsigned int _fenceCount;
    unsigned long long _fenceName;
    BSAtomicSignal *_fenceInvalid;
    NSObject<OS_dispatch_semaphore> *_fenceInvalidSemaphore;
    unsigned int _caFencePort;
    BSMachPortSendRight *_caFence;
    BSMachPortReceiveRight *_preFenceReceiveRight;
    unsigned long long _preFenceGenerationToken;
    BSMachPortReceiveRight *_preFenceTriggerReceiveRight;
    unsigned int _lastAssertionName;
}

+ (id)sharedInstance;
- (id)_newAssertionForTriggerPort:(unsigned int)arg1;
- (id)_newFenceHandle;
- (id)init;

@end

