//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKProximitySensorHardwareBase.h"

@interface BKGrapeIntegratedProximitySensorHardware : BKProximitySensorHardwareBase
{
    int _lockedHIDMode;
}

+ (id)sensorConfiguredForWatch;
+ (id)sensorConfiguredForHandheld;
@property int lockedHIDMode; // @synthesize lockedHIDMode=_lockedHIDMode;
- (id)lowLevelDescriptionForMode:(long long)arg1 pocketTouchesExpected:(_Bool)arg2;
- (void)reallySetMode:(long long)arg1 pocketTouchesExpected:(_Bool)arg2;
- (int)_HIDDetectionModeForDetectionMode:(long long)arg1 pocketTouchesExpected:(_Bool)arg2;
- (void)reallyResetCalibration;

@end

