//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BKEventClientDelegate-Protocol.h"

@class NSMapTable, NSString;
@protocol OS_dispatch_queue;

@interface BKHIDEventKeyCommandDescriptorMap : NSObject <BKEventClientDelegate>
{
    NSObject<OS_dispatch_queue> *_clientQueue;
    NSMapTable *_descriptorMap;
    NSMapTable *_pidToClientMapping;
}

+ (id)sharedInstance;
- (void)clientDied:(id)arg1;
- (long long)descriptorMatchSpecifiesDescriptor:(id)arg1 withEventFocusProperties:(id)arg2;
- (void)clearDescriptorsForPID:(int)arg1;
- (void)setKeyCommandDescriptors:(id)arg1 forEventFocusProperties:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

