//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BKIOHIDServiceDisappearanceObserver-Protocol.h"

@class NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface BKHIDEventSenderCache : NSObject <BKIOHIDServiceDisappearanceObserver>
{
    NSMutableDictionary *_senderIDToSenderInfo;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableDictionary *senderIDToSenderInfo; // @synthesize senderIDToSenderInfo=_senderIDToSenderInfo;
- (void)removeSenderInfo:(id)arg1;
- (void)addSenderInfo:(id)arg1;
- (id)senderInfoForSenderID:(unsigned long long)arg1;
- (void)sync;
- (void)serviceDidDisappear:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

