//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BKHIDEventSenderCache, BKHumanPresenceHIDEventProcessor;
@protocol OS_dispatch_queue;

@interface BKHIDSystemInterface : NSObject
{
    struct __IOHIDEventSystem *_HIDEventSystem;
    struct __IOHIDEventSystemClient *_HIDEventSystemClient;
    NSObject<OS_dispatch_queue> *_gsEventQueue;
    NSObject<OS_dispatch_queue> *_queue;
    _Bool _open;
    _Bool _fullyInitialized;
    BKHumanPresenceHIDEventProcessor *_humanPresenceEventProcessor;
    BKHIDEventSenderCache *_senderCache;
}

+ (id)sharedInstance;
@property(getter=isFullyInitialized) _Bool fullyInitialized; // @synthesize fullyInitialized=_fullyInitialized;
@property(getter=isOpen) _Bool open; // @synthesize open=_open;
@property(retain) BKHIDEventSenderCache *senderCache; // @synthesize senderCache=_senderCache;
@property(retain, nonatomic) BKHumanPresenceHIDEventProcessor *humanPresenceEventProcessor; // @synthesize humanPresenceEventProcessor=_humanPresenceEventProcessor;
- (void)unregisterIOHIDServicesCallback:(CDUnknownFunctionPointerType)arg1 matchingDictionary:(id)arg2 target:(void *)arg3 refCon:(void *)arg4;
- (void)registerIOHIDServicesCallback:(CDUnknownFunctionPointerType)arg1 matchingDictionary:(id)arg2 target:(void *)arg3 refCon:(void *)arg4;
- (id)IOHIDServicesMatching:(id)arg1;
- (void)_beginHandlingEvents;
- (struct __IOHIDEvent *)systemEventOfType:(unsigned int)arg1 matchingEvent:(struct __IOHIDEvent *)arg2 options:(unsigned int)arg3;
- (void)injectGSEvent:(struct __GSEvent *)arg1;
- (void)injectHIDEvent:(struct __IOHIDEvent *)arg1;
- (void)setSystemProperty:(id)arg1 forKey:(id)arg2;
- (id)systemPropertyForKey:(id)arg1;
- (void)startServer;
- (void)startEventProcessors;
- (void)startHIDSystem;
- (_Bool)ping;
- (void)dealloc;
- (id)initWithQueue:(id)arg1;

@end

