//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <BackBoardServices/BKSHIDEventRouterManagerBase.h>

@class BKEventFocusManager, NSMapTable, NSObject;
@protocol OS_dispatch_queue;

@interface BKHIDEventRouterManager : BKSHIDEventRouterManagerBase
{
    NSObject<OS_dispatch_queue> *_queue;
    BKEventFocusManager *_accessor_eventFocusManager;
    NSMapTable *_cachedDescriptorsToRouterDestinations;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMapTable *cachedDescriptorsToRouterDestinations; // @synthesize cachedDescriptorsToRouterDestinations=_cachedDescriptorsToRouterDestinations;
- (long long)queue_routerDestinationForDescriptor:(id)arg1;
- (id)_descriptorForHIDEvent:(struct __IOHIDEvent *)arg1;
- (void)_updateRoutersForCurrentSystemApp;
- (void)_queue_setEventRouters:(id)arg1;
- (void)setEventFocusManager:(id)arg1;
- (id)eventFocusManager;
- (void)setEventRouters:(id)arg1;
- (void)configureEventRouters:(id)arg1 forPID:(int)arg2;
- (id)systemAppDestinationWithDisplay:(id)arg1;
- (id)destinationForDescriptor:(id)arg1 onDisplay:(id)arg2;
- (id)destinationForEvent:(struct __IOHIDEvent *)arg1 onDisplay:(id)arg2;
- (void)dealloc;
- (id)init;

@end

