//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BKIOHIDServiceDisappearanceObserver-Protocol.h"
#import "BKIOHIDServiceMatchObserver-Protocol.h"

@class BKIOHIDServiceMatcher, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface BKHumanPresenceHIDEventProcessor : NSObject <BKIOHIDServiceMatchObserver, BKIOHIDServiceDisappearanceObserver>
{
    NSMutableDictionary *_queue_displayUUIDToSensorRecords;
    NSObject<OS_dispatch_queue> *_queue;
    BKIOHIDServiceMatcher *_presenceServiceMatcher;
    BKIOHIDServiceMatcher *_proximityServiceMatcher;
}

@property(retain, nonatomic) BKIOHIDServiceMatcher *proximityServiceMatcher; // @synthesize proximityServiceMatcher=_proximityServiceMatcher;
@property(retain, nonatomic) BKIOHIDServiceMatcher *presenceServiceMatcher; // @synthesize presenceServiceMatcher=_presenceServiceMatcher;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) NSMutableDictionary *displayUUIDToSensorRecords; // @synthesize displayUUIDToSensorRecords=_queue_displayUUIDToSensorRecords;
- (_Bool)filterEvent:(struct __IOHIDEvent *)arg1 fromSender:(id)arg2;
- (void)getStatus:(unsigned long long *)arg1 presence:(_Bool *)arg2 proximityInCentimeters:(double *)arg3 forDisplayUUID:(id)arg4;
- (void)_setPresence:(_Bool)arg1 forDisplayUUID:(id)arg2;
- (void)_setProximityInCentimeters:(double)arg1 forDisplayUUID:(id)arg2;
- (void)serviceDidDisappear:(id)arg1;
- (void)matcher:(id)arg1 servicesDidMatch:(id)arg2;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

