//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSBundle, NSPointerArray, NSString;

@interface BKImageSequence : NSObject
{
    long long _maximumImageCount;
    double _scale;
    NSPointerArray *_images;
    NSBundle *_bundle;
    NSString *_basename;
    NSString *_idiomSuffix;
}

@property(retain, nonatomic) NSString *idiomSuffix; // @synthesize idiomSuffix=_idiomSuffix;
@property(copy, nonatomic) NSString *basename; // @synthesize basename=_basename;
@property(retain, nonatomic) NSBundle *bundle; // @synthesize bundle=_bundle;
@property(retain, nonatomic) NSPointerArray *images; // @synthesize images=_images;
@property(readonly, nonatomic) double scale; // @synthesize scale=_scale;
@property(readonly, nonatomic) long long maximumImageCount; // @synthesize maximumImageCount=_maximumImageCount;
- (void)_loadAllImages;
- (struct CGImage *)_imageAtIndex:(long long)arg1;
- (id)_idiomSuffix;
- (struct CGImage *)_createImageForIndex:(unsigned long long)arg1 basename:(id)arg2 scale:(double)arg3 idiom:(id)arg4 bundle:(id)arg5;
- (id)allImages;
- (struct CGImage *)imageAtIndex:(long long)arg1;
- (void)dealloc;
- (id)initWithBasename:(id)arg1 bundle:(id)arg2 imageCount:(long long)arg3 scale:(double)arg4;

@end

