//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BSInvalidatable-Protocol.h"

@class BKHIDSystemInterface, NSDictionary, NSString;
@protocol BKIOHIDServiceMatchObserver, OS_dispatch_queue;

@interface BKIOHIDServiceMatcher : NSObject <BSInvalidatable>
{
    _Bool _startedMatching;
    _Bool _invalidated;
    NSDictionary *_matchingDictionary;
    Class _serviceClass;
    id <BKIOHIDServiceMatchObserver> _observer;
    NSObject<OS_dispatch_queue> *_observerQueue;
    BKHIDSystemInterface *_HIDSystem;
}

@property(retain, nonatomic) BKHIDSystemInterface *HIDSystem; // @synthesize HIDSystem=_HIDSystem;
@property(nonatomic) __weak NSObject<OS_dispatch_queue> *observerQueue; // @synthesize observerQueue=_observerQueue;
@property(nonatomic) __weak id <BKIOHIDServiceMatchObserver> observer; // @synthesize observer=_observer;
@property(nonatomic) Class serviceClass; // @synthesize serviceClass=_serviceClass;
@property(copy, nonatomic) NSDictionary *matchingDictionary; // @synthesize matchingDictionary=_matchingDictionary;
- (void).cxx_destruct;
- (id)_servicesForIOHIDServiceRefs:(id)arg1;
- (void)_servicesAdded:(id)arg1;
- (void)invalidate;
- (void)startObserving:(id)arg1 queue:(id)arg2;
- (id)existingServices;
- (void)dealloc;
- (id)initWithMatchingDictionary:(id)arg1 serviceClass:(Class)arg2 HIDSystem:(id)arg3;
- (id)initWithMatchingDictionary:(id)arg1 HIDSystem:(id)arg2;
- (id)initWithUsagePage:(int)arg1 usage:(int)arg2 builtIn:(_Bool)arg3 HIDSystem:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

