//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BKIOHIDService, BKSHIDEventDescriptor, NSString;

@interface BKKeyboardInfo : NSObject
{
    _Bool _swallowEvents;
    _Bool _capsLockOn;
    _Bool _capsLockRomanSwitchMode;
    unsigned char _countryCode;
    _Bool _shouldActivateByGesture;
    unsigned int _keyboardType;
    BKIOHIDService *_service;
    unsigned long long _keyDownCount;
    NSString *_keyboardLayout;
    NSString *_keyboardLanguage;
    struct __GSKeyboard *__gsKeyboard;
    BKSHIDEventDescriptor *_keyboardActivationEventDescriptor;
}

+ (id)keyboardInfoWithIOHIDService:(id)arg1;
@property(retain, nonatomic) BKSHIDEventDescriptor *keyboardActivationEventDescriptor; // @synthesize keyboardActivationEventDescriptor=_keyboardActivationEventDescriptor;
@property(readonly, nonatomic) _Bool shouldActivateByGesture; // @synthesize shouldActivateByGesture=_shouldActivateByGesture;
@property(readonly, nonatomic) struct __GSKeyboard *_gsKeyboard; // @synthesize _gsKeyboard=__gsKeyboard;
@property(copy, nonatomic) NSString *keyboardLanguage; // @synthesize keyboardLanguage=_keyboardLanguage;
@property(copy, nonatomic) NSString *keyboardLayout; // @synthesize keyboardLayout=_keyboardLayout;
@property(nonatomic) unsigned int keyboardType; // @synthesize keyboardType=_keyboardType;
@property(nonatomic) unsigned char countryCode; // @synthesize countryCode=_countryCode;
@property(nonatomic) _Bool capsLockRomanSwitchMode; // @synthesize capsLockRomanSwitchMode=_capsLockRomanSwitchMode;
@property(nonatomic, getter=isCapsLockOn) _Bool capsLockOn; // @synthesize capsLockOn=_capsLockOn;
@property(nonatomic, getter=shouldSwallowEvents) _Bool swallowEvents; // @synthesize swallowEvents=_swallowEvents;
@property(nonatomic) unsigned long long keyDownCount; // @synthesize keyDownCount=_keyDownCount;
@property(retain, nonatomic) BKIOHIDService *service; // @synthesize service=_service;
- (void)setCapsLockLEDOn:(_Bool)arg1;
- (void)setExternalKeyboardEventSource;
@property(readonly, nonatomic) BKSHIDEventDescriptor *keyboardActivationChangeEventDescriptor;
@property(readonly, nonatomic, getter=isKeyboardActive) _Bool keyboardActive;
- (id)description;
- (void)dealloc;
- (id)initWithService:(id)arg1;

@end

