//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BKGestureRecognizerDelegate-Protocol.h"
#import "BKIOHIDServiceDisappearanceObserver-Protocol.h"
#import "BKIOHIDServiceMatchObserver-Protocol.h"

@class BKIOHIDServiceMatcher, NSArray, NSMutableArray, NSString;
@protocol BKKeyboardManagerDelegate, OS_dispatch_queue;

@interface BKKeyboardManager : NSObject <BKGestureRecognizerDelegate, BKIOHIDServiceMatchObserver, BKIOHIDServiceDisappearanceObserver>
{
    NSMutableArray *_attachedKeyboards;
    id <BKKeyboardManagerDelegate> _delegate;
    NSMutableArray *_usableKeyboards;
    NSMutableArray *_gestureRecognizers;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_queue> *_calloutQueue;
    BKIOHIDServiceMatcher *_keyboardServiceMatcher;
}

@property(retain, nonatomic) BKIOHIDServiceMatcher *keyboardServiceMatcher; // @synthesize keyboardServiceMatcher=_keyboardServiceMatcher;
@property(nonatomic) id <BKKeyboardManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)gestureRecognizer:(id)arg1 didChangeState:(long long)arg2;
- (void)_queue_stopWatchingForGestures:(id)arg1;
- (void)_queue_watchForGestures:(id)arg1;
- (void)_queue_usableKeyboardDetached:(id)arg1;
- (void)_queue_usableKeyboardAttached:(id)arg1;
- (void)_queue_keyboardRemoved:(id)arg1;
- (void)serviceDidDisappear:(id)arg1;
- (void)_queue_keyboardsDetected:(id)arg1;
- (void)matcher:(id)arg1 servicesDidMatch:(id)arg2;
- (id)keyboardInfoForSenderID:(unsigned long long)arg1;
@property(readonly, copy, nonatomic) NSArray *attachedKeyboards;
- (void)start;
@property(readonly, copy) NSString *debugDescription;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

