//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BKEventClientDelegate-Protocol.h"

@class BKProximitySensorHardwareBase, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface BKProximitySensorInterface : NSObject <BKEventClientDelegate>
{
    long long _currentMode;
    NSMutableDictionary *_pidToClients;
    NSObject<OS_dispatch_queue> *_clientQueue;
    _Bool _pocketTouchesExpected;
    _Bool _objectWithinProximityShouldIgnoreTouches;
    _Bool _disabled;
    unsigned int _estimatedProxPowerAssertionID;
    NSObject<OS_dispatch_source> *_estimatedProxShutoffTimer;
    BKProximitySensorHardwareBase *_sensorHardware;
}

+ (id)sharedInstance;
@property(nonatomic, getter=isDisabled) _Bool disabled; // @synthesize disabled=_disabled;
@property(retain, nonatomic) BKProximitySensorHardwareBase *sensorHardware; // @synthesize sensorHardware=_sensorHardware;
@property(nonatomic) unsigned int estimatedProxPowerAssertionID; // @synthesize estimatedProxPowerAssertionID=_estimatedProxPowerAssertionID;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *estimatedProxShutoffTimer; // @synthesize estimatedProxShutoffTimer=_estimatedProxShutoffTimer;
@property(nonatomic) _Bool objectWithinProximityShouldIgnoreTouches; // @synthesize objectWithinProximityShouldIgnoreTouches=_objectWithinProximityShouldIgnoreTouches;
- (void)clientDied:(id)arg1;
- (void)setUILockState:(unsigned long long)arg1 source:(unsigned long long)arg2;
- (void)setPocketTouchesExpected:(_Bool)arg1;
- (unsigned long long)requestEstimatedProximityEventsWithTimeout:(double)arg1;
- (void)handleProximityEvent:(struct __IOHIDEvent *)arg1 fromSender:(id)arg2;
- (void)setEventClientWithBundleID:(id)arg1;
- (void)resetCalibration;
- (void)requestProximityMode:(long long)arg1;
- (_Bool)clientRequestedProximityMode:(int)arg1 processID:(int)arg2 clientPort:(id)arg3;
- (_Bool)isObjectWithinProximity;
- (_Bool)isDetectionActive;
- (id)_existingClientForPID:(int)arg1;
- (_Bool)_removeClient:(id)arg1;
- (_Bool)_addClient:(id)arg1;
- (void)_updateClientPID:(int)arg1 clientPort:(id)arg2 withDetectionMode:(long long)arg3;
- (id)_createClientForPID:(int)arg1 sendRight:(id)arg2 queue:(id)arg3;
- (void)_updateProximityDetectionMode;
- (long long)_requestedMode;
- (long long)_effectiveMode;
- (unsigned long long)_queue_requestEstimatedProximityEventsWithTimeout:(double)arg1;
- (void)_queue_cancelEstimatedProximityEventShutoffTimerAndResetMode:(_Bool)arg1;
- (void)_queue_cancelEstimatedProximityEventShutoffTimer;
- (long long)_queue_effectiveMode;
- (_Bool)_queue_removeClient:(id)arg1;
- (_Bool)_queue_addClient:(id)arg1;
- (void)_queue_updateProximityDetectionMode;
- (void)dealloc;
- (id)initWithHardware:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

