//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BKIOHIDServiceDisappearanceObserver-Protocol.h"
#import "BKIOHIDServiceMatchObserver-Protocol.h"

@class BKEventDestination, BKIOHIDService, BKIOHIDServiceMatcher, NSString;

@interface BKProximitySensorHardwareBase : NSObject <BKIOHIDServiceMatchObserver, BKIOHIDServiceDisappearanceObserver>
{
    _Bool _objectWithinProximity;
    _Bool _proximityDetectionInActiveMode;
    long long _baseMode;
    unsigned long long _lockSource;
    BKIOHIDServiceMatcher *_digitizerServiceMatcher;
    BKEventDestination *_eventDestination;
    BKIOHIDService *_digitizerService;
}

@property(retain, nonatomic) BKIOHIDService *digitizerService; // @synthesize digitizerService=_digitizerService;
@property(retain) BKEventDestination *eventDestination; // @synthesize eventDestination=_eventDestination;
@property(retain, nonatomic) BKIOHIDServiceMatcher *digitizerServiceMatcher; // @synthesize digitizerServiceMatcher=_digitizerServiceMatcher;
@property(nonatomic) unsigned long long lockSource; // @synthesize lockSource=_lockSource;
@property long long baseMode; // @synthesize baseMode=_baseMode;
@property(getter=isProximityDetectionInActiveMode) _Bool proximityDetectionInActiveMode; // @synthesize proximityDetectionInActiveMode=_proximityDetectionInActiveMode;
@property(getter=isObjectWithinProximity) _Bool objectWithinProximity; // @synthesize objectWithinProximity=_objectWithinProximity;
- (void)reallySetMode:(long long)arg1 pocketTouchesExpected:(_Bool)arg2;
- (void)reallyResetCalibration;
- (id)lowLevelDescriptionForMode:(long long)arg1 pocketTouchesExpected:(_Bool)arg2;
- (void)_setObjectWithinProximity:(_Bool)arg1 notify:(_Bool)arg2;
- (void)_sendProxEvent:(struct __IOHIDEvent *)arg1 toDestination:(id)arg2 objectWithinProximity:(_Bool)arg3;
- (void)configureBaseModeForALS;
- (void)setMode:(long long)arg1 pocketTouchesExpected:(_Bool)arg2;
- (void)handleProximityEvent:(struct __IOHIDEvent *)arg1 fromSender:(id)arg2;
- (_Bool)isValidEvent:(struct __IOHIDEvent *)arg1 fromSender:(id)arg2;
- (void)setEventsClientWithBundleID:(id)arg1;
- (void)resetCalibration;
- (void)serviceDidDisappear:(id)arg1;
- (void)matcher:(id)arg1 servicesDidMatch:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

