//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKEventClient.h"

@interface BKProximityDetectionClient : BKEventClient
{
    long long _requestedMode;
}

@property long long requestedMode; // @synthesize requestedMode=_requestedMode;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
@property(readonly, nonatomic, getter=isValid) _Bool valid;
- (void)dealloc;

@end

