//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BKGestureRecognizer.h"

@class BKKeyboardInfo, BKSHIDEventDescriptor;

@interface BKSmartKeyboardGestureRecognizer : BKGestureRecognizer
{
    BKKeyboardInfo *_keyboard;
    BKSHIDEventDescriptor *_activationChangeEventDescriptor;
}

@property(retain, nonatomic) BKSHIDEventDescriptor *activationChangeEventDescriptor; // @synthesize activationChangeEventDescriptor=_activationChangeEventDescriptor;
@property(retain, nonatomic) BKKeyboardInfo *keyboard; // @synthesize keyboard=_keyboard;
- (void)_handleEvent:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithSmartKeyboard:(id)arg1 activationChangeEventDescriptor:(id)arg2;

@end

