//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BKHIDSystemInterface;

@interface BKSmartCoverHIDEventProcessor : NSObject
{
    _Bool _attached;
    _Bool _unknownState;
    BKHIDSystemInterface *_hidSystemInterface;
    unsigned long long _supportedSensors;
    unsigned long long _sensorsRequiredForOpenState;
    unsigned long long _disengagedSensors;
    long long _state;
}

+ (_Bool)isSmartCoverSupported;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(nonatomic, getter=isUnknownState) _Bool unknownState; // @synthesize unknownState=_unknownState;
@property(nonatomic, getter=isAttached) _Bool attached; // @synthesize attached=_attached;
@property(nonatomic) unsigned long long disengagedSensors; // @synthesize disengagedSensors=_disengagedSensors;
@property(nonatomic) unsigned long long sensorsRequiredForOpenState; // @synthesize sensorsRequiredForOpenState=_sensorsRequiredForOpenState;
@property(nonatomic) unsigned long long supportedSensors; // @synthesize supportedSensors=_supportedSensors;
@property(retain, nonatomic) BKHIDSystemInterface *hidSystemInterface; // @synthesize hidSystemInterface=_hidSystemInterface;
- (_Bool)filterEvent:(struct __IOHIDEvent *)arg1 fromSender:(id)arg2;
@property(readonly, nonatomic, getter=isSmartCoverClosed) _Bool smartCoverClosed;
- (void)_postEvent:(struct __IOHIDEvent *)arg1 toSender:(id)arg2;
- (_Bool)_smartCoverSensorsDidDisengage:(unsigned long long)arg1;
- (_Bool)_smartCoverSensorsDidEngage:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithHIDSystemInterface:(id)arg1;
- (unsigned long long)_currentMaskForUsage:(unsigned int)arg1 HIDSystem:(id)arg2 mask:(unsigned long long *)arg3 maskIfEngaged:(unsigned long long *)arg4;
- (id)initWithHIDSystemInterface:(id)arg1 supportedHES:(unsigned long long)arg2 disengagedHES:(unsigned long long)arg3 attached:(_Bool)arg4 unknownState:(_Bool)arg5;

@end

