//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface BKTetherController : NSObject
{
    int _tetherState;
    unsigned int _demoCardConnection;
    int _lastOrientationCode;
    _Bool _orientationNotificationsDisabled;
}

+ (id)sharedInstance;
@property(nonatomic, getter=isOrientationNotificationDisabled) _Bool orientationNotificationDisabled; // @synthesize orientationNotificationDisabled=_orientationNotificationsDisabled;
- (void)updatePreferencesIfNeeded;
- (_Bool)_reverseTetheringActive;
- (_Bool)_serviceExists:(struct __CFString *)arg1;
- (void)setDitheringEnabled:(int)arg1;
- (void)noteInterfaceOrientationChangedWithInterfaceOrientation:(int)arg1;
- (void)_handleDemoModeChanged;
- (_Bool)usesDisplayPortTethering;
- (_Bool)isTethered;
- (void)_setTetherState:(int)arg1;
- (void)_postDisplayPortNotificationCode:(int)arg1;
- (unsigned int)_demoCardConnection;
- (void)dealloc;
- (id)init;

@end

