//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BKEventDestination, BKIOHIDService;

@interface BKTouchPadInfo : NSObject
{
    _Bool _determinedMaxForce;
    float _maxForce;
    BKIOHIDService *_service;
    BKEventDestination *_currentDestination;
    long long _touchCount;
}

@property(nonatomic) _Bool determinedMaxForce; // @synthesize determinedMaxForce=_determinedMaxForce;
@property(nonatomic) float maxForce; // @synthesize maxForce=_maxForce;
@property(nonatomic) long long touchCount; // @synthesize touchCount=_touchCount;
@property(retain, nonatomic) BKEventDestination *currentDestination; // @synthesize currentDestination=_currentDestination;
@property(retain, nonatomic) BKIOHIDService *service; // @synthesize service=_service;
- (id)description;
- (void)dealloc;

@end

