//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BKHIDSystemInterface, BKSystemAppSentinel;

@interface BKWatchdogService : NSObject
{
    BKHIDSystemInterface *_hidSystem;
    BKSystemAppSentinel *_systemAppSentinel;
}

@property(retain, nonatomic) BKSystemAppSentinel *systemAppSentinel; // @synthesize systemAppSentinel=_systemAppSentinel;
@property(retain, nonatomic) BKHIDSystemInterface *hidSystem; // @synthesize hidSystem=_hidSystem;
- (_Bool)isAlive;
- (void)dealloc;
- (id)init;

@end

